version: '3.2'

services:
    django:
      build: .
      stdin_open: true
      tty: true
      ports:
        - "8000:8000"
        - "5678:5678"
      working_dir: /app
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - ..:/app
      environment:
        - "PYTHONUNBUFFERED=1"
      expose:
        - "8000"
      depends_on:
        - mariadb

    celery:
      build: .
      stdin_open: true
      tty: true
      working_dir: /app
      command: celery -A ecommerce worker -l info
      volumes:
        - ..:/app
      environment:
        - "PYTHONUNBUFFERED=1"
      expose:
        - "8000"
      depends_on:
        - mariadb
        
      

    mariadb:
      image: mariadb:10.2
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: techvins
        MYSQL_USER: myusername
        MYSQL_HOST: localhost
        MYSQL_PASSWORD: mypassword
      volumes:
       - ../data/mariadb:/var/lib/mysql
    
    # prestashop:
    #   image: prestashop/prestashop:1.7-7.0
    #   ports:
    #     - "8080:80"
    #   environment:
    #     PS_DEV_MODE: 0
    #     PS_INSTALL_AUTO: 0
    #     MYSQL_ROOT_PASSWORD: root
    #     MYSQL_DATABASE: techvins
    #     MYSQL_USER: myusername
    #     MYSQL_HOST: localhost
    #     MYSQL_PASSWORD: mypassword
    #   volumes:
    #    - ../data/mariadb:/var/lib/mysql
    adh_redis:
      image: redis