version: '3.2'

services:
    ragavi:
      image: techvins/repo:adh_prod
      working_dir: /app
      #command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - "/data/ragavi/nginx/static:/app/nginx_static"
        - "/data/ragavi/nginx/media:/app/media"
        - "/data/host_tmp:/host_tmp"
        - "/etc/localtime:/etc/localtime"

      environment:
        - "PYTHONUNBUFFERED=1"
      
      # volumes:
      #   - ${NGINX_DATA}/sitemap:/var/www/html/sitemap/
      expose:
        - "8000"

    ragavi_celery:
      image: techvins/repo:adh_prod
      working_dir: /app
      command: celery -A ecommerce worker -l info
      volumes:
        - "/data/ragavi/nginx/static:/app/nginx_static"
        - "/data/ragavi/nginx/media:/app/media"
        - "/data/host_tmp:/host_tmp" 
      environment:
        - "PYTHONUNBUFFERED=1"
      # volumes:
      #   - ${NGINX_DATA}/sitemap:/var/www/html/sitemap/
      expose:
        - "8000"


    rgv_imgproxy:
      image: darthsim/imgproxy
      volumes:
        - /data/ragavi/nginx/static/:/var/www/html/static
        - /data/ragavi/nginx/media/:/var/www/html/static/media
      environment:
          - 1=ssssssss1
          - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/var/www/html
          - IMGPROXY_ENFORCE_WEBP=true
          - IMGPROXY_DEVELOPMENT_ERRORS_MODE=true
          - IMGPROXY_MAX_SRC_RESOLUTION=50
    rgv_redis:
      image: redis
      volumes:
        - /data/ragavi/redis/data/:/data
networks:
  default:
    external:
      name: corevision-overlay
