"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a0mafwe5y77c_9ej#vc(w9_**umkgj98t^gcba$iriy!!7bd_='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
 
    
]

THIRD_PARTY_APPS = [
    'django_extensions',
    'rest_framework',
    # 'captcha',
    'ckeditor',
    # 'django_celery_results',
    # 'simple_history',
    'nested_inline',
    'django_filters',
    'taggit'
    
]

LOCAL_APPS = [
    'blogs',
    'core',
    'users',
    'shop',
    'communication'
]

INSTALLED_APPS += THIRD_PARTY_APPS
INSTALLED_APPS += LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.backends.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',

]

ROOT_URLCONF = 'ecommerce.urls'
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
from ecommerce.my_loader import MyLoader
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': ['templates'],
        'APP_DIRS': True,

        'OPTIONS': {
            # 'loader': 'ecommerce.my_loader.MyLoader',
            # 'loader':MyLoader(),
            'environment': 'ecommerce.jinja_env.environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.globals',
            ],
        },
    },

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


LOGIN_URL = '/user/login.html'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'techvins',
        'USER':'root',
        'PASSWORD':'root',
        'HOST':'mariadb',
        'PORT':'3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.User"

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'             
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
] 
# Media Folder Settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"


RUPEE_SYMBOL = "Rs."
MOBILE_SMS_SERVICE = ''
FROM_EMAIL="info@aadhara.in"

SESSION_COOKIE_NAME="session_id"
SESSION_CART_NAME="session_cart"
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True

RAZORPAY_KEY = 'rzp_test_Ce4jygv0ISuYB0'
RAZORPAY_SECRET = 'nREyXN3nOtFKeBaNZW1Qvf8u'
LOGO_URL= "logo/ad-logo.png"

CELERY_BROKER_URL = 'redis://adh_redis/0'
DEFAULT_FROM_EMAIL = 'info@aadhara.in'
ADMINS = (
    ('Vinay Malik', 'vinay@techvins.com'),
    ('Nitishraj Singh', 'nitishraj@techvins.com'),
)
SERVER_EMAIL="support@aadhara.in"
MANAGERS = ADMINS

EXCEPTION_EMAIL_TO = [
    'vinay@techvins.com',
    'nitishraj@techvins.com',
]

#Order Pickup Address
PICKUP_WAREHOUSE_NAME="Adhara house"
PICKUP_NAME="adhara"
PICKUP_ADDRESS="adhara house no 23 jp road"
PICKUP_CITY="jaipur"
PICKUP_STATE="Rajasthan"
PICKUP_PINCODE="302021"
PICKUP_PHONE_NO="9656770402"

#END 
STOREFRONT_NAME="Aadhara"
try:
    from ecommerce.local_settings import *
except ImportError:
    pass
