# Generated by Django 3.2.5 on 2022-01-19 05:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('url', models.TextField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('status_code', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('type', models.SmallIntegerField(choices=[(1, 'Country'), (2, 'State'), (3, 'District'), (4, 'City')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.CharField(max_length=120)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(help_text='minimum width: 775px', max_length=250, null=True, upload_to='upload/homepage/')),
                ('priority', models.IntegerField(default=1, help_text='1 is higher than 2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfiguration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('editable', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStaticPage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='This is for SEO', max_length=150, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical static page',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTextPlaceholder',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('value', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical text placeholder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('button_text', models.CharField(max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 is higher than 2')),
                ('image', models.ImageField(max_length=250, null=True, upload_to='upload/homepage/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('message', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='This is for SEO', max_length=150, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('city_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.citystate')),
            ],
        ),
    ]
