# Generated by Django 3.2.5 on 2022-01-19 05:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(null=True, upload_to='upload/blog/thumbnail/')),
                ('priority', models.IntegerField(default=1, help_text='1 is higher than 2')),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(10, 'Draft'), (20, 'Published'), (30, 'Hidden')], default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
